name: Build, Test, and Prepare for Local Deployment

on:
  push:
    branches: [ Development ]

jobs:
  setup-and-build:
    runs-on: self-hosted


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Frontend Setup
      - name: Install UI dependencies
        working-directory: ./OstadUI
        run: npm install

      - name: Build frontend
        working-directory: ./OstadUI
        run: npm run build

      - name: Run frontend tests (if available)
        working-directory: ./OstadUI
        run: |
          echo "No tests yet"
          
      - name: Show success message
        run: echo "✅ Build and tests passed"
